language: go
go:
  - tip
before_install:
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/modocache/gover

script:
  - go test ./...
  - for dir in *; do if [ -d "${dir}" ]; then for file in ${dir}/*_test.go; do if [ -f "${file}" ]; then go test -coverprofile=${dir}/profile.coverprofile github.com/hiwane/qeconv/${dir}; break; fi; done; fi; done
  - gover
  - $HOME/gopath/bin/goveralls -coverprofile=gover.coverprofile -service drone.io -repotoken jKxviW3LDc1bNmRYgq1idpdFV984rGeeq


